apply plugin: 'java-library'

java.sourceCompatibility = 11
java.targetCompatibility = 11
if (JavaVersion.current().isJava9Compatible()) {
  compileJava.options.release.set(11)
}

[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  api "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  api "com.github.kotcrab.vis-ui:vis-ui:$visUiVersion"
  api "space.earlygrey:shapedrawer:$shapeDrawerVersion"

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
  testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
  testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
}
test {
  useJUnitPlatform()
}

jar {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
